{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "DocuSign Admin API",
    "description" : "An API for an organization administrator to manage organizations, accounts and users",
    "termsOfService" : "https://www.docusign.com/company/terms-and-conditions/developers",
    "contact" : {
      "name" : "DocuSign Developer Center",
      "url" : "https://developers.docusign.com",
      "email" : "devcenter@docusign.com"
    },
    "version" : "v2.1"
  },
  "servers" : [ {
    "url" : "https://api.docusign.net/Management"
  } ],
  "tags" : [ {
    "name" : "IdentityProviders",
    "description" : "Methods to get a list of identity providers."
  }, {
    "name" : "ReservedDomains",
    "description" : "Methods to get a list of reserved domains."
  }, {
    "name" : "Users",
    "description" : "Methods to manage users in an account."
  }, {
    "name" : "eSignUserManagement",
    "description" : "Methods to manage eSignature users in an account."
  }, {
    "name" : "MultiProductUserManagement",
    "description" : "Methods to manage multi-product users in an account."
  }, {
    "name" : "UserExport",
    "description" : "Methods for exporting a user list."
  }, {
    "name" : "AccountSettingsExport",
    "description" : "Methods and objects to get account information."
  }, {
    "name" : "UserImport",
    "description" : "Methods to import users.\n\nTo ensure your CSV is properly formatted, use the\n[Sample Bulk Add CSV file](https://admin.docusign.com/static-resources/organization-user-import.csv)\n as a template.\n\nYou can add up to 2,000 users to an account and include up to 50 accounts per import. The maximum number of users per import is 8,000."
  }, {
    "name" : "Organization",
    "description" : "Methods for working with organizations."
  }, {
    "name" : "AccountSettingsImport",
    "description" : "Methods and objects to update account settings."
  }, {
    "name" : "SingleAccountUserImport",
    "description" : "Methods to import users."
  }, {
    "name" : "DataDeletion",
    "description" : "Methods to delete user data. After a user is closed, an account or organization administrator can use these methods to delete the user's account data."
  }, {
    "name" : "AccountCloning",
    "description" : "Methods to clone accounts."
  } ],
  "paths" : {
    "/v2/organizations" : {
      "get" : {
        "tags" : [ "Organization" ],
        "summary" : "Returns a list of organizations that the authenticated user belongs to.",
        "description" : "Returns a list of organizations that the authenticated user belongs to.\n\nNote that the DocuSign Admin API only returns JSON, not XML.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `organization_read`.\n\nThis method requires user authentication. It will fail with an [application access token](/docs/admin-api/admin101/application-auth/).",
        "operationId" : "Organization_Organization_GetListV2",
        "security" : [ {
          "accessCode" : [ "organization_read" ]
        } ],
        "x-ds-methodname" : "getOrganizations",
        "x-ds-method" : "getOrganizations",
        "x-ds-service" : "Accounts",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/data_redaction/accounts/{accountId}/user" : {
      "post" : {
        "tags" : [ "DataDeletion" ],
        "summary" : "Deletes membership data for a user on an account.",
        "description" : "Deletes the data for a single account membership for a specified user.\n\nTo call this endpoint: \n* You must be an administrator (or delegated administrator) of the specified account.\n* The user must have been closed for at least 24 hours.\n\n**Note:** After a user's data is deleted for every account to which they belong, their user-level data will automatically be deleted.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_data_redact`.\n",
        "operationId" : "DataRedaction_RedactIndividualMembershipData",
        "security" : [ {
          "accessCode" : [ "user_data_redact" ]
        } ],
        "x-ds-methodname" : "redactIndividualMembershipData",
        "x-ds-method" : "redactIndividualMembershipData",
        "x-ds-service" : "Accounts",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/accounts/{accountId}/permissions" : {
      "get" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Returns the list of permission profiles in an account.",
        "description" : "Returns the list of permission profiles in an account.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `permission_read`.\n\n",
        "operationId" : "Account_Accounts_GetPermissionProfilesV2",
        "security" : [ {
          "accessCode" : [ "permission_read" ]
        } ],
        "x-ds-methodname" : "getPermissions",
        "x-ds-method" : "getPermissions",
        "x-ds-service" : "Accounts",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/accounts/{accountId}/groups" : {
      "get" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Returns the list of groups in an account.",
        "description" : "Returns the list of groups in an account.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `group_read`.\n",
        "operationId" : "Account_Accounts_GetGroupsV2",
        "security" : [ {
          "accessCode" : [ "group_read" ]
        } ],
        "x-ds-methodname" : "getGroups",
        "x-ds-method" : "getGroups",
        "x-ds-service" : "Accounts",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/exports/user_list" : {
      "get" : {
        "tags" : [ "UserExport" ],
        "summary" : "Returns a list of pending and completed export requests.",
        "description" : "Returns a list of pending and completed export requests.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.\n",
        "operationId" : "OrganizationExport_OrganizationExport_Get",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getUserListExports",
        "x-ds-method" : "getUserListExports",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "UserExport" ],
        "summary" : "Creates a user list export request.",
        "description" : "Create a user list export request.\n\nThis method initiates a user list export request. You specify the type of export request as JSON in the body of method, like this:\n\n``` json\n{\n\t\"type\": \"organization_memberships_export\"\n}\n```\n\nThe export request type is one of three values:\n\n| Value                                      | Description                                                                                             |\n| :-----------------------[...]",
        "operationId" : "OrganizationExport_OrganizationExport_Insert",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "createUserListExport",
        "x-ds-method" : "createUserListExport",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/exports/account_settings" : {
      "get" : {
        "tags" : [ "AccountSettingsExport" ],
        "summary" : "Returns a list of pending and completed account settings export request.",
        "description" : "Returns a list of pending and completed account settings export requests.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.",
        "operationId" : "OrganizationExport_OrganizationExport_GetAccountCompare",
        "security" : [ {
          "accessCode" : [ "account_read" ]
        } ],
        "x-ds-methodname" : "getAccountSettingsExports",
        "x-ds-method" : "getAccountSettingsExports",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "AccountSettingsExport" ],
        "summary" : "Creates a  new account settings export request.",
        "description" : "Creates a new account settings export request.\n\nTo learn more about exporting account settings,\nsee [Account Settings Export][guide-export]\nin the DocuSign Admin Guide.\n\nYou can export settings for up to 40 accounts at a time.\n\nSpecify the accounts whose settings you are requesting as JSON in the body of the request, like this:\n\n``` json\n{\n  \"accounts\":\t[\n  \t{ \"account_id\": \"9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e\"},\n  \t{ \"account_id\": \"624e3e00-xx[...]",
        "operationId" : "OrganizationExport_OrganizationExport_AccountCompare",
        "security" : [ {
          "accessCode" : [ "account_read" ]
        } ],
        "x-ds-methodname" : "createAccountSettingsExport",
        "x-ds-method" : "createAccountSettingsExport",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/exports/user_list/{exportId}" : {
      "get" : {
        "tags" : [ "UserExport" ],
        "summary" : "Returns the results for single user list export request.",
        "description" : "Returns the results for single user list export request.\n\nGiven an export ID, this method returns the results of a single user list export request.\nTo get a list of all the export requests, use `getUserListExports`.\n\nNote that the `metadata_url` property of the response from `createUserListExport` is a read-to-use HTTP GET request to get the status.\n\nThe results are available through a URL that\nyou can access through the `results` property of the response.\nFor e[...]",
        "operationId" : "OrganizationExport_OrganizationExport_GetByExportId",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getUserListExport",
        "x-ds-method" : "getUserListExport",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      },
      "delete" : {
        "tags" : [ "UserExport" ],
        "summary" : "Deletes a single user list export request.",
        "description" : "Deletes a single user list export request.\nUse this method to delete pending or completed user export requests.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.\n\n",
        "operationId" : "OrganizationExport_OrganizationExport_DeleteByExportId",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "deleteUserListExport",
        "x-ds-method" : "deleteUserListExport",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/exports/account_settings/{exportId}" : {
      "get" : {
        "tags" : [ "AccountSettingsExport" ],
        "summary" : "Returns the results for a single account settings export request.",
        "description" : "Returns the results for a single account settings export request.\n\nGiven an export ID, this method returns the results of an account settings export request.\nTo get a list of all the export requests, use `getAccountSettingsExports`.\n\nThe results are available through a URL that\nyou can access through the `results` property of the response.\nFor example, to get the URL of first result you might use\n`results[0].url`\n\nThe settings export is formatted like this:\n\n[...]",
        "operationId" : "OrganizationExport_OrganizationExport_GetAccountSettingsExportByExportId",
        "security" : [ {
          "accessCode" : [ "account_read" ]
        } ],
        "x-ds-methodname" : "getAccountSettingsExport",
        "x-ds-method" : "getAccountSettingsExport",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      },
      "delete" : {
        "tags" : [ "AccountSettingsExport" ],
        "summary" : "Deletes a single account settings export request.",
        "description" : "Deletes a single account settings export request.\nAny data associated with the request is also deleted.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.\n",
        "operationId" : "OrganizationExport_OrganizationExport_DeleteByAccountSettingsExportId",
        "security" : [ {
          "accessCode" : [ "account_read" ]
        } ],
        "x-ds-methodname" : "deleteAccountSettingsExport",
        "x-ds-method" : "deleteAccountSettingsExport",
        "x-ds-service" : "BulkExports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/account_settings" : {
      "get" : {
        "tags" : [ "AccountSettingsImport" ],
        "summary" : "Returns the details and metadata for Bulk Account Settings Import requests in the organization.",
        "description" : "Returns the details and metadata for Bulk Account Settings Import requests in the organization.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.",
        "operationId" : "OrganizationImport_OrganizationImportAccountSettings_Get",
        "security" : [ {
          "accessCode" : [ "account_read" ]
        } ],
        "x-ds-methodname" : "getBulkAccountSettingsImports",
        "x-ds-method" : "getBulkAccountSettingsImports",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "AccountSettingsImport" ],
        "summary" : "Creates a new account settings import request.",
        "description" : "Creates a new account settings import request.\n\nThe request for this method consists of\nthe contents of a CSV\nfile.\n\nYou can export your current settings as a CSV file with\n[AccountSettingsExport: createAccountSettingsExport](/docs/admin-api/reference/bulkoperations/accountsettingsexport/createaccountsettingsexport/)\nand use it as the basis\nof the changes you want to import.\n\n\nTo learn more about the format\nof a settings CSV file, see\n[Preparing a CSV for a[...]",
        "operationId" : "OrganizationImport_OrganizationImportAccountSettings_Post",
        "security" : [ {
          "accessCode" : [ "account_write" ]
        } ],
        "x-ds-methodname" : "addBulkAccountSettingsImport",
        "x-ds-method" : "addBulkAccountSettingsImport",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/account_settings/{importId}" : {
      "get" : {
        "tags" : [ "AccountSettingsImport" ],
        "summary" : "Returns the details/metadata for a Bulk Account Settings Import request.",
        "description" : "Returns the details/metadata for a Bulk Account Settings Import request.\n\nGiven an import ID, this method returns the results of an account settings import request.\nTo get a list of all the import requests, use `getAccountSettingsImports`.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `account_read`.\n",
        "operationId" : "OrganizationImport_OrganizationImportAccountSettings_GetById",
        "security" : [ {
          "accessCode" : [ "account_read" ]
        } ],
        "x-ds-methodname" : "getBulkAccountSettingsImport",
        "x-ds-method" : "getBulkAccountSettingsImport",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      },
      "delete" : {
        "tags" : [ "AccountSettingsImport" ],
        "summary" : "Deletes a Bulk Account Settings Import request.",
        "description" : "Deletes a single account settings import request.\nAny data associated with the request is also deleted.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `account_write`.",
        "operationId" : "OrganizationImport_OrganizationImportAccountSettings_DeleteById",
        "security" : [ {
          "accessCode" : [ "account_write" ]
        } ],
        "x-ds-methodname" : "deleteBulkAccountSettingsImport",
        "x-ds-method" : "deleteBulkAccountSettingsImport",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/bulk_users/add" : {
      "post" : {
        "tags" : [ "UserImport" ],
        "summary" : "Creates a request to import new users into an account.",
        "description" : "Creates a request to import *new* users.\n\nYour CSV import file is made up of a header row with the column headers and a row of user or account data for each user you want to add to an account. Only new users can be imported. Any changes to existing users will be ignored. To make changes to existing users, use [UserImport:updateBulkUserImports][imports].\n\nTo ensure your CSV is properly formatted, use the\n[Sample Bulk Add CSV file](https://admin.docusign.com/static-re[...]",
        "operationId" : "OrganizationImport_OrganizationImportUsers_Insert",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "addBulkUserImport",
        "x-ds-method" : "addBulkUserImport",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/add" : {
      "post" : {
        "tags" : [ "SingleAccountUserImport" ],
        "summary" : "Import request for adding a user to a single account within the organization.",
        "description" : "Import request for adding a user to a single account within the organization.\nThis method lets you upload user information without requiring an AccountId column.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n",
        "operationId" : "OrganizationImport_OrganizationImportSingleAccountUsers_Insert",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "createBulkImportSingleAccountAddUsersRequest",
        "x-ds-method" : "createBulkImportSingleAccountAddUsersRequest",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/bulk_users/update" : {
      "post" : {
        "tags" : [ "UserImport" ],
        "summary" : "Bulk updates information for existing users.",
        "description" : "Bulk updates information for existing users.\n\nYour CSV import file is made up of a header row with the column headers and a row of user or account data for each user you want to add to an account. \n\n\n**Update limit:** You can update up to 2,000 users on an account and include up to 50 accounts per import. The maximum number of updated users per import is 8,000.\n\nThis method requires the following HTTP headers:\n\n| Header | Value |\n| :--- |  :--- |\n| Content-Typ[...]",
        "operationId" : "OrganizationImport_OrganizationImportUsers_Update",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "updateBulkUserImports",
        "x-ds-method" : "updateBulkUserImports",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/update" : {
      "post" : {
        "tags" : [ "SingleAccountUserImport" ],
        "summary" : "Import request for updating users for a single account\nwithin the organization.",
        "description" : "Import request for updating users for a single account\nwithin the organization.\n\nThis method lets you upload user information without requiring an `AccountId` column.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n\n",
        "operationId" : "OrganizationImport_OrganizationImportSingleAccountUsers_Update",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "createBulkImportSingleAccountUpdateUsersRequest",
        "x-ds-method" : "createBulkImportSingleAccountUpdateUsersRequest",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/bulk_users/close" : {
      "post" : {
        "tags" : [ "UserImport" ],
        "summary" : "Creates a request to close the accounts of existing users.",
        "description" : "Creates a request to close the accounts of existing users.\n\nGiven a CSV list of users, close their accounts.\n\nYour CSV import file is made up of a header row with the column headers and a row of user or account data for each user whose account you want to close.\n\nTo ensure your CSV is properly formatted, use the\n[Sample Bulk Update CSV file](https://admin.docusign.com/static-resources/organization-user-update-import.csv)\n as a template. The following table descri[...]",
        "operationId" : "OrganizationImport_OrganizationImportUsers_Close",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "closeBulkUserImportRequest",
        "x-ds-method" : "closeBulkUserImportRequest",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/bulk_users/close_external" : {
      "post" : {
        "tags" : [ "UserImport" ],
        "summary" : "Closes external memberships.",
        "description" : "Closes external memberships.\n\nExternal memberships are users who have an email address at a verified domain but do not belong to the organization.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n",
        "operationId" : "OrganizationImport_OrganizationImportUsers_CloseExternal",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "closeBulkExternalUserImportRequest",
        "x-ds-method" : "closeBulkExternalUserImportRequest",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/bulk_users" : {
      "get" : {
        "tags" : [ "UserImport" ],
        "summary" : "Gets a list of all of the user import requests.",
        "description" : "Gets a list of all of the user import requests.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationImport_OrganizationImportUsers_Get",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getBulkUserImportRequests",
        "x-ds-method" : "getBulkUserImportRequests",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/bulk_users/{importId}" : {
      "get" : {
        "tags" : [ "UserImport" ],
        "summary" : "Returns the details of a single user import request.",
        "description" : "Returns the details of a single user import request.\n\nUse this method to check the status of the request by looking at the `status` property of the response.\nOnce the status becomes `completed` (or fails), use this method to get the details.\n\nTo get a list of all of the user import requests, use `getBulkUserImportRequests`.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationImport_OrganizationImportUsers_GetById",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getBulkUserImportRequest",
        "x-ds-method" : "getBulkUserImportRequest",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      },
      "delete" : {
        "tags" : [ "UserImport" ],
        "summary" : "Deletes a specific user import request.",
        "description" : "Deletes a specific import request and its results.\n\nTo delete a user, see [closeBulkUserImportRequest](/docs/admin-api/reference/bulkoperations/userimport/closebulkuserimportrequest/).\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "OrganizationImport_OrganizationImportUsers_DeleteById",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "deleteBulkUserImport",
        "x-ds-method" : "deleteBulkUserImport",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/imports/bulk_users/{importId}/results_csv" : {
      "get" : {
        "tags" : [ "UserImport" ],
        "summary" : "Given the ID of a user import request,\nreturn the CSV file that was imported.",
        "description" : "Returns the contents of the CSV file\nassociated with a user import request.\n\nThe results have an additional column,\n`ProcessingResults`,\nthat describes the results of importing that row.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.\n",
        "operationId" : "OrganizationImport_OrganizationImportUsers_GetCSVResults",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getBulkUserImportCSV",
        "x-ds-method" : "getBulkUserImportCSV",
        "x-ds-service" : "BulkImports",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/identity_providers" : {
      "get" : {
        "tags" : [ "IdentityProviders" ],
        "summary" : "Returns the list of identity providers for an organization.",
        "description" : "Returns the list of identity providers for an organization.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `identity_provider_read`.",
        "operationId" : "Organization_GetIdentityProviders",
        "security" : [ {
          "accessCode" : [ "identity_provider_read" ]
        } ],
        "x-ds-methodname" : "getIdentityProviders",
        "x-ds-method" : "getIdentityProviders",
        "x-ds-service" : "IdentityProviders",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/data_redaction/organizations/{organizationId}/user" : {
      "post" : {
        "tags" : [ "DataDeletion" ],
        "summary" : "Deletes data for one or more of a user's account memberships.",
        "description" : "Deletes data for one or more of a user's account memberships.\n\nTo call this endpoint: \n* You must be an organization administrator (or delegated administrator) with permission to manage the specified accounts or the user's email domain.\n* The user must have been closed for at least 24 hours.\n\n**Note:** After a user's data is deleted for every account to which they belong, their user-level data will automatically be deleted.\n\n[Required authentication scopes](/docs[...]",
        "operationId" : "DataRedaction_RedactIndividualUserData",
        "security" : [ {
          "accessCode" : [ "user_data_redact" ]
        } ],
        "x-ds-methodname" : "redactIndividualUserData",
        "x-ds-method" : "redactIndividualUserData",
        "x-ds-service" : "Organizations",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/reserved_domains" : {
      "get" : {
        "tags" : [ "ReservedDomains" ],
        "summary" : "Returns the list of reserved domains for the organization.",
        "description" : "Returns the list of reserved domains for the organization.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `domain_read`.",
        "operationId" : "Organization_GetReservedDomains",
        "security" : [ {
          "accessCode" : [ "domain_read" ]
        } ],
        "x-ds-methodname" : "getReservedDomains",
        "x-ds-method" : "getReservedDomains",
        "x-ds-service" : "ReservedDomains",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/users/profiles" : {
      "post" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Updates a user's information.",
        "description" : "Updates a user's information.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "User_Users_UpdateV2",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "updateUser",
        "x-ds-method" : "updateUser",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/users/email_addresses" : {
      "post" : {
        "tags" : [ "Users" ],
        "summary" : "Updates a user's email address.",
        "description" : "Updates a user's email address.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n",
        "operationId" : "User_Users_UpdateEmailAddressesV2",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "updateEmailAddress",
        "x-ds-method" : "updateEmailAddress",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/users/{userId}/accounts" : {
      "delete" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Closes a user's memberships.",
        "description" : "Closes a user's memberships.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n\nThis method requires user authentication. It will fail with an [application access token](/docs/admin-api/admin101/application-auth/).",
        "operationId" : "User_Users_CloseMembershipsV2",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "closeMemberships",
        "x-ds-method" : "closeMemberships",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/users" : {
      "get" : {
        "tags" : [ "Users" ],
        "summary" : "Returns information about the users in an organization.",
        "description" : "Returns information about the users in an organization.\n\nYou must include at least one of the following query parameters in the request:\n\n- `account_id`: The ID of an account associated with the organization.\n- `organization_reserved_domain_id`: The ID of one of the organization's reserved domains.\n- `email`: An email address associated with the users that you want to return.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationUser_OrganizationUsers_GetV2",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getUsers",
        "x-ds-method" : "getUsers",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Creates a new user.",
        "description" : "Creates a new user.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n",
        "operationId" : "OrganizationUser_Users_AddV2",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "createUser",
        "x-ds-method" : "createUser",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/users/{userId}/memberships/{membershipId}" : {
      "post" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Activates user memberships.",
        "description" : "Activates user memberships.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n",
        "operationId" : "OrganizationUser_Users_ActivateMembershipV2",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "activateMembership",
        "x-ds-method" : "activateMembership",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/users/profile" : {
      "get" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Returns historical information about users with a specific email address.\n",
        "description" : "Returns historical information about users with a specific email address.\n**Note:** The `email` query parameter is _required_.\n\n\nTo get a list of users in an organization,\nuse [Users: getUsers](/docs/admin-api/reference/usermanagement/users/getusers/)\ninstead.\n\nFor example, the following request gets information about\naccounts that use `max@example.net` as an email address:\n\n\n```json\nGET /Management/v2/organizations/96e994fa-xxxx-xxxx-xxxx-c5fe9d1ccd10/users[...]",
        "operationId" : "OrganizationUser_OrganizationUsers_GetProfileV2",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getUserProfiles",
        "x-ds-method" : "getUserProfiles",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/users/{userId}/identities" : {
      "delete" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Deletes user identities.",
        "description" : "Deletes user identities.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n",
        "operationId" : "OrganizationUser_DeleteIdentitiesV2",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "deleteIdentities",
        "x-ds-method" : "deleteIdentities",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2/organizations/{organizationId}/accounts/{accountId}/users" : {
      "post" : {
        "tags" : [ "eSignUserManagement" ],
        "summary" : "Adds users to an account.",
        "description" : "Adds users to an account.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.\n\n",
        "operationId" : "OrganizationUser_OrganizationUsers_PostAccountUsersV2",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "addUsers",
        "x-ds-method" : "addUsers",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Returns a list of DSGroups.",
        "description" : "Returns a list of DSGroups.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "DocuSignGroupsv21_GetDSGroups_V2_1",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getDSGroups",
        "x-ds-method" : "getDSGroups",
        "x-ds-service" : "DSGroups",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Creates a new DSGroup.",
        "description" : "Creates a new DSGroup.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "DocuSignGroupsv21_AddDSGroup_V2_1",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "addDSGroup",
        "x-ds-method" : "addDSGroup",
        "x-ds-service" : "DSGroups",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Returns details about a single DSGroup.",
        "description" : "Returns details about a single DSGroup.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "DocuSignGroupsv21_GetDSGroup_V2_1",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getDSGroup",
        "x-ds-method" : "getDSGroup",
        "x-ds-service" : "DSGroups",
        "x-ds-in-sdk" : true
      },
      "delete" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Deletes a DSGroup.",
        "description" : "Deletes a DSGroup.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "DocuSignGroupsv21_DeleteDSGroup_V2_1",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "deleteDSGroup",
        "x-ds-method" : "deleteDSGroup",
        "x-ds-service" : "DSGroups",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}/users" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Gets a list of users in a DSGroup.",
        "description" : "Gets a list of users in a DSGroup.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "DocuSignGroupsv21_GetDSGroupUsers_V2_1",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getDSGroupUsers",
        "x-ds-method" : "getDSGroupUsers",
        "x-ds-service" : "DSGroups",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Adds a list of users to a DSGroup.",
        "description" : "Adds a list of users to a DSGroup.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "DocuSignGroupsv21_AddDSGroupUsers_V2_1",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "addDSGroupUsers",
        "x-ds-method" : "addDSGroupUsers",
        "x-ds-service" : "DSGroups",
        "x-ds-in-sdk" : true
      },
      "delete" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Removes a list of users from a DSGroup.",
        "description" : "Removes a list of users from a DSGroup. In the request body, you can specify users by ID or email address. If both parameters are included, the email address parameter will be ignored.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "DocuSignGroupsv21_RemoveDSGroupUsers_V2_1",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "removeDSGroupUsers",
        "x-ds-method" : "removeDSGroupUsers",
        "x-ds-service" : "DSGroups",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/products/permission_profiles" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Gets products associated with the account and the available permission profiles.",
        "description" : "Gets products associated with the account and the available permission profiles.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationProductPermissionProfile_GetProductPermissionProfiles",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getProductPermissionProfiles",
        "x-ds-method" : "getProductPermissionProfiles",
        "x-ds-service" : "ProductPermissionProfiles",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/products/users/{userId}/permission_profiles" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Retrieves a user's product permission profiles by user ID.",
        "description" : "Retrieves a list of a user's permission profiles for each account's product. The user is specified by the ID provided in the `userId` path parameter.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationProductPermissionProfile_GetUserProductPermissionProfiles",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getUserProductPermissionProfiles",
        "x-ds-method" : "getUserProductPermissionProfiles",
        "x-ds-service" : "ProductPermissionProfiles",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Assigns permission profiles for a user by user ID.",
        "description" : "Sets permission profiles for one or more products for a given user. The user is specified by the `userId` path parameter.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "OrganizationProductPermissionProfile_PostUserProductPermissionProfiles",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "addUserProductPermissionProfiles",
        "x-ds-method" : "addUserProductPermissionProfiles",
        "x-ds-service" : "ProductPermissionProfiles",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/users" : {
      "post" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Creates and updates a multi-product user.",
        "description" : "Creates and updates a multi-product user.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "OrganizationUser_OrganizationUsers_PostAccountUsersV2_1",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "addOrUpdateUser",
        "x-ds-method" : "addOrUpdateUser",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/users/dsprofile" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Retrieves the DS profile for a user specified by email address.",
        "description" : "Gets information about a user specified by the `email` query parameter.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationUser_OrganizationUsers_GetDSProfiles",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getUserDSProfilesByEmail",
        "x-ds-method" : "getUserDSProfilesByEmail",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/users/{userId}/dsprofile" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Retrieves the DS profile for a user specified by ID.",
        "description" : "Gets information about a user specified by the `userId` query parameter.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationUser_OrganizationUsers_GetDSProfileByUserId",
        "security" : [ {
          "accessCode" : [ "user_read" ]
        } ],
        "x-ds-methodname" : "getUserDSProfile",
        "x-ds-method" : "getUserDSProfile",
        "x-ds-service" : "Users",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/products/users" : {
      "delete" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Revokes a user's access to one or more products.",
        "description" : "Revokes a specified user's access to one or more products.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "OrganizationProductPermissionProfile_RemoveUserProducts",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "removeUserProductPermission",
        "x-ds-method" : "removeUserProductPermission",
        "x-ds-service" : "ProductPermissionProfiles",
        "x-ds-in-sdk" : true
      }
    },
    "/v2.1/organizations/{organizationId}/accounts/{accountId}/products/permission_profiles/users" : {
      "get" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Retrieves a user's product permission profiles by email address.",
        "description" : "Retrieves a list of a user's permission profiles for each account's product. The user is specified by the email address provided in the `email` query parameter.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_read`.",
        "operationId" : "OrganizationProductPermissionProfile_GetUserProductPermissionProfilesByEmail",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "getUserProductPermissionProfilesByEmail",
        "x-ds-method" : "getUserProductPermissionProfilesByEmail",
        "x-ds-service" : "ProductPermissionProfiles",
        "x-ds-in-sdk" : true
      },
      "post" : {
        "tags" : [ "MultiProductUserManagement" ],
        "summary" : "Assigns permission profiles for a user by email address.",
        "description" : "Sets permission profiles for one or more products for a given user. The user is specified by the `email` property in the request body.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `user_write`.",
        "operationId" : "OrganizationProductPermissionProfile_PostUserProductPermissionProfilesByEmail",
        "security" : [ {
          "accessCode" : [ "user_write" ]
        } ],
        "x-ds-methodname" : "addUserProductPermissionProfilesByEmail",
        "x-ds-method" : "addUserProductPermissionProfilesByEmail",
        "x-ds-service" : "ProductPermissionProfiles",
        "x-ds-in-sdk" : true
      }
    },
    "/v1/organizations/{organizationId}/assetGroups/accounts" : {
      "get" : {
        "tags" : [ "AccountCloning" ],
        "summary" : "Get asset group accounts for an organization.",
        "description" : "Returns a list of asset group accounts for an organization.\n\nAn asset group is a set of modules, products, plans, and charges purchased for your organization. An asset group account is an account that has been linked to an asset group.\n\nTo call this endpoint:\n* You must be an administrator for the specified organization.\n\n[Required authentication scopes](/docs/admin-api/admin101/auth/): `asset_group_account_read`.",
        "operationId" : "OrganizationProvisionAssetGroup_GetAssetGroupAccountsByOrg",
        "security" : [ {
          "accessCode" : [ "asset_group_account_read" ]
        } ],
        "x-ds-methodname" : "getAssetGroupAccounts",
        "x-ds-method" : "getAssetGroupAccounts",
        "x-ds-service" : "ProvisionAssetGroup",
        "x-ds-in-sdk" : true
      }
    },
    "/v1/organizations/{organizationId}/assetGroups/accountClone" : {
      "post" : {
        "tags" : [ "AccountCloning" ],
        "summary" : "Clone an existing DocuSign account.",
        "description" : "Clones an existing DocuSign account. Cloning an account copies the plan items and eSignature settings. Users, templates, and permission profiles are _not_ copied into the target account. The new account will linked to the same organization.\n\nIn the request body, specify the source account you are cloning by its ID. You can get the IDs for your organization's asset group accounts using the [getAssetGroupAccounts](/docs/admin-api/reference/accountprovisioning/accountclon[...]",
        "operationId" : "OrganizationProvisionAssetGroup_CloneAssetGroupAccount",
        "security" : [ {
          "accessCode" : [ "asset_group_account_clone_write" ]
        } ],
        "x-ds-methodname" : "cloneAssetGroupAccount",
        "x-ds-method" : "cloneAssetGroupAccount",
        "x-ds-service" : "ProvisionAssetGroup",
        "x-ds-in-sdk" : true
      }
    },
    "/v1/organizations/{organizationId}/assetGroups/accountClones" : {
      "get" : {
        "tags" : [ "AccountCloning" ],
        "summary" : "Gets all asset group account clones for an organization.",
        "description" : "Retrieves all the cloned accounts for an organization.\n\nTo call this endpoint:\n* You must be an administrator for the specified organization.\n\n[Required scopes](/docs/admin-api/admin101/auth/): `asset_group_account_clone_read`.",
        "operationId" : "OrganizationProvisionAssetGroup_GetAssetGroupAccountClonesByOrgId",
        "security" : [ {
          "accessCode" : [ "asset_group_account_clone_read" ]
        } ],
        "x-ds-methodname" : "getAssetGroupAccountClonesByOrgId",
        "x-ds-method" : "getAssetGroupAccountClonesByOrgId",
        "x-ds-service" : "ProvisionAssetGroup",
        "x-ds-in-sdk" : true
      }
    },
    "/v1/organizations/{organizationId}/assetGroups/{assetGroupId}/accountClones/{assetGroupWorkId}" : {
      "get" : {
        "tags" : [ "AccountCloning" ],
        "summary" : "Gets information about a single cloned account.",
        "description" : "Gets information about a cloned account by the `assetGroupWorkId`.\n\nTo call this endpoint:\n* You must be an administrator for the specified organization.\n\n[Required scopes](/docs/admin-api/admin101/auth/): `asset_group_account_clone_read`.",
        "operationId" : "OrganizationProvisionAssetGroup_GetAssetGroupAccountClone",
        "security" : [ {
          "accessCode" : [ "asset_group_account_clone_read" ]
        } ],
        "x-ds-methodname" : "getAssetGroupAccountClone",
        "x-ds-method" : "getAssetGroupAccountClone",
        "x-ds-service" : "ProvisionAssetGroup",
        "x-ds-in-sdk" : true
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "accessCode" : {
        "type" : "oauth2",
        "description" : "OAuth2 Access code Grant",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://account.docusign.com/oauth/auth",
            "tokenUrl" : "https://account.docusign.com/oauth/auth",
            "scopes" : {
              "organization_read" : "",
              "user_data_redact" : "",
              "permission_read" : "",
              "group_read" : "",
              "user_read" : "",
              "account_read" : "",
              "account_write" : "",
              "user_write" : "",
              "identity_provider_read" : "",
              "domain_read" : ""
            }
          }
        }
      }
    }
  },
  "x-ds-categories" : [ {
    "name" : "IdentityProviders",
    "summary" : "Methods to get a list of identity providers.",
    "description" : "Methods to get a list of identity providers."
  }, {
    "name" : "ReservedDomains",
    "summary" : "Methods to get a list of reserved domains.",
    "description" : "Methods to get a list of reserved domains."
  }, {
    "name" : "UserManagement",
    "summary" : "Methods to manage users in an account.",
    "description" : "Methods to manage users in an account."
  }, {
    "name" : "BulkOperations",
    "summary" : "Methods to import and export users and accounts.",
    "description" : "Methods to import and export users and accounts."
  }, {
    "name" : "Organization",
    "summary" : "Methods for working with organizations.",
    "description" : "Methods for working with organizations."
  }, {
    "name" : "AccountProvisioning",
    "summary" : "Methods to provision accounts in your organization.",
    "description" : "Methods to provision accounts in your organization."
  } ],
  "x-original-swagger-version" : "2.0"
}